version: "3.7"

services:
  app:
    image: my-llamindex-works
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    volumes:
      - .:/app
    tty: true
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
  nebula: # コンテナ起動後にコンテナ内で「/usr/local/nebula/scripts/nebula.service start all」を実行する必要がある
    build:
      context: .
      dockerfile: Dockerfile.nebula
    tty: true
    ports:
      - 9559:9559
      - 9669:9669
      - 9779:9779
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/Admin-999
      - NEO4JLABS_PLUGINS=["apoc"]

volumes:
  weaviate_data: